### ISSUE TITLE
add ability to communicate with autoannotate with cyrest

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#110]
for example:
ask aa to annotate the network but not show the annotations
given a cluster id return the annotation for that cluster
given a node which cluster it belongs to and which annotation belongs to 

add more if you think of any.

**Comment by mikekucera** [comment]
Cytoscape 3.6 adds the ability to return JSON from commands. So I could modify the existing annotate command to return JSON instead of having to create a new REST endpoint. Would that be ok? I can also add new commands for the additional functionality you requested.

**Comment by risserlin** [comment]
What is the difference between the two options?  How would that effect how I currently interact with the command?

**Comment by mikekucera** [comment]
I talked to David and Christian about this and I think commands are the way to go. Since you are already using commands there shouldn't be much change in how you call them. It will be much easier for me to update the current commands than to create a new set of REST endpoints. The only catch is I have to increase the Cytoscape version requirement to 3.6.

**Comment by mikekucera** [comment]
Hi Ruth, does the following json format work for you?

```
{
  "data": [
    {
      "label": "glycogen glucan biosynthetic",
      "nodes": [15971, 15569, 14912, 14830]
    },
    {
      "label": "recruitment axin cadherin",
      "nodes": [15922, 15387, 14832, 14593]
    },
...
```
