### ISSUE TITLE
Copy annotations when a subnetwork is created.

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#129]
when user clones the current network that has annotations or creates a subnetwork that has annotations copy the annotations over to the newly created network.

**Comment by mikekucera** [comment]
An event is fired when a network is created, but this event does not say which network it was cloned from (if any). So if there is more than one network, and a new network is created, I don't know which of the existing networks to copy the annotations from. I also don't think it should be automatic because the user might not want to copy annotations.

Instead I'd like to propose a new menu item in the AutoAnnotate panel called "copy annotations from...". It opens a dialog that allows the user to select an existing network and copy its annotations onto the current network. 

I think we will have to limit the list of existing networks to subnetworks within the same network collection, because the nodes will have the same SUIDs, otherwise we would have to match the nodes by some other attribute, and at that point it probably makes more sense to recreate the annotations from scratch.

**Comment by risserlin** [comment]
Given that a cloned network will have identical annotations to the parent I think the more important use case is copying over annotations to a subnetwork.  Maybe we should start there.  I amended the name of the issue to reflect this.

Some useful options to allow with the annotation copy:
do/do not copy clusters that are not 100% in subnetwork.

**Comment by mikekucera** [comment]
I just discovered that there is a way to tell when a network is cloned and to get its "parent" network. This is the same relationship that shows up in the network panel when "Show Network Provenance Hierarchy" is turned on.

So there are two ways this could work...

1) Fully automatic. When a network is cloned we automatically copy over all existing annotations from the parent. If the subnetwork contains less nodes then clusters containing the missing nodes are not copied.

2) Manual. Add a menu item to the AutoAnnotate panel called "copy annotations". This opens a dialog where the user can select which annotations to copy, and additional options such as "do/do not copy clusters that are not 100% in the network". The limitation of only being allowed to copy from a subnetwork in the same collection still applies.

I feel 2 is more flexible and useful. The user can choose exactly what to copy. They can copy from any subnetwork, not just the parent. And they can copy more than once if they want duplicates for some reason.

Which do you prefer Ruth?

**Comment by risserlin** [comment]
Couldn't we have both :).  Similar to the way autoannotate has the quick start and advanced options.  By default it does option 1 but user can choose to do option 2 if they want.

**Comment by mikekucera** [comment]
No problem :)
