### ISSUE TITLE
Automatically redraw annotations on session reload.

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#15]
Create network
Annotate network
Save Session
Close and re-open session
On reloaded session annotations are gone.  
example sessions: https://www.dropbox.com/s/41o3u4fnu9wz8eb/Mesen_vs_Immuno_rnaseq_EM_annot.cys?dl=0

**Comment by mikekucera** [comment]
This seems to be working with the latest build of AutoAnnotate. Did you create the session with an older build? Because I changed the format of the saved annotation model a couple of times during development.

**Comment by risserlin** [comment]
by latest build do you mean RC2?

I just tried again.  I created the annotation in RC2 and then reopen the session in RC2 and you can see them for a few seconds and then they get deleted.

How can I verify that I am using RC2?  I am pretty sure I am but I can't find where I can see this for sure.

**Comment by mikekucera** [comment]
That is due to bug #1. Cytoscape provides no way to get a handle on the existing annotations so they have to be erased and redrawn when the session is loaded. As long as the annotation sets are available in the dropdown then it is working as expected.

I plan to (hopefully) fix this problem with annotations in Cytoscape 3.4. Then the annotations won't have to be erased when the session is loaded.

**Comment by risserlin** [comment]
Ok.  I had no idea that the annotations were there.  After the session loads can you trigger the selection event to redraw everything automatically?

**Comment by mikekucera** [comment]
Yes, that is a good idea.
