### ISSUE TITLE
question? aggregated summary

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#183]
Just a question: What does Unique Values represent for the AutoAnnotate: Create Summary Network for the field GS_DESCR . I'm assuming that this is the gene-set description of the most significant gene-set of the cluster (fdr) and that explains that there are ties.

![Screen Shot 2022-12-02 at 1 52 55 PM](https://user-images.githubusercontent.com/7570379/205367605-454b52a0-861c-4555-96f1-4f6b1c4fcdba.png)

**Comment by mikekucera** [comment]
Unique Values takes all the values for an attribute, removes the duplicates, then concatenates the results (using "," as delimiter).
 
For example, a set of nodes with values `"a", "a", "a", "b", "b", "c"` would become one string with the value `"a,b,c"`.

That's why I added the new aggregator called Cluster Label. Instead of making a long label with all the geneset names smashed together it uses the cluster label from AA.

**Comment by veroniquevoisin** [comment]
Ok, Thanks! I was thinking that another field would be useful: label of most significant node (fdr) but then it makes AA not generic.

**Comment by mikekucera** [comment]
> I was thinking that another field would be useful: label of most significant node (fdr) but then it makes AA not generic.

Its ok to have custom aggregators for EM networks. They just don't show up for non-EM networks.

This gets complicated because in a mastermap there are multiple fdr columns. Would it be ok use the label of the node that has the most significant fdr across all datasets?

**Comment by veroniquevoisin** [comment]
yes, that would work!

**Comment by mikekucera** [comment]
What if more than one node has the same most significant fdr value? Should it return a concatenated list of the names, or just pick one name at random?

**Comment by veroniquevoisin** [comment]
The most accurate would be a concatenated list of the names. We could test
that first and observe the frequency of ties. That would be my suggestion.
