### ISSUE TITLE
Handle hidden nodes in annotations

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#29]
Ignore nodes that are marked as hidden when calculating clusters and annotations.

**Comment by abouchakra** [comment]
I am currently using 6 data sets in EM 3 and I wanted to annotate just a subset by hiding the rest, however the hidden data will still become annotated. To me this is more like a bug and not just an enhancement. Because the only option at this moment is to recreate the Map with only the data set that I am interested in exploring.

**Comment by mikekucera** [comment]
Similar problem to #88.

Another workaround might be to select the visible nodes/edges, click the "new network from selection" button, then using AA on the network that is created.

Unfortunately clusterMaker2 does not support clustering a subset of nodes. But it might be possible to automate the process of creating a new subnetwork, clustering it, then applying the annotations to the original network.

**Comment by mikekucera** [comment]
Fixed in commit f3bb784
